version: '3'

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes: 
            - ./data:/data/
        networks:
            - mongo-network

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: root
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        networks:
            - mongo-network
        restart: unless-stopped
    
    app:
        image: app
        container_name: nest-app
        ports:
            - "3001:3001"
        depends_on:
            - mongo-express
        environment:
            MONGO_URI_DEV: "mongodb://mongo:27017/price_comparator"
        networks:
            - mongo-network
        restart: unless-stopped

networks:
    mongo-network:
        driver: bridge
