import { Injectable } from '@nestjs/common'

import { Category } from './category.enum'

@Injectable()
export class CategoryService {
  constructor() {}

  mapFromMercadona(id: number): Category {
    console.log('jacinto category', id)
    // The big switch
    switch (id) {
      case 112:
        return Category.AceiteVinagreSal
      case 115:
        return Category.Especias
      case 116:
        return Category.Salsas
      case 117:
        return Category.Salsas
      case 156:
        return Category.Agua
      case 163:
        return Category.Refrescos
      case 158:
        return Category.Refrescos
      case 159:
        return Category.Refrescos
      case 161:
        return Category.Refrescos
      case 162:
        return Category.Refrescos
      case 135:
        return Category.Aperitivos
      case 133:
        return Category.Aperitivos
      case 132:
        return Category.Aperitivos
      case 118:
        return Category.Arroz
      case 121:
        return Category.Legumbres
      case 120:
        return Category.PastaFideos
      case 89:
        return Category.AzucarEdulcorante
      case 95:
        return Category.ChiclesCaramelosGolosinas
      case 92:
        return Category.Chocolate
      case 97:
        return Category.ChiclesCaramelosGolosinas
      case 90:
        return Category.MermeladaMiel
      case 216:
        return Category.Bebe
      case 219:
        return Category.Bebe
      case 218:
        return Category.Bebe
      case 217:
        return Category.Bebe
      case 164:
        return Category.Cerveza
      case 166:
        return Category.Cerveza
      case 181:
        return Category.Licores
      case 174:
        return Category.SidraCava
      case 168:
        return Category.TintoVeranoSangria
      case 170:
        return Category.Vino
      case 173:
        return Category.Vino
      case 171:
        return Category.Vino
      case 169:
        return Category.Vino
      case 86:
        return Category.CacaoSoluble
      case 81:
        return Category.Cafe
      case 83:
        return Category.Cafe
      case 84:
        return Category.Cafe
      case 88:
        return Category.TeInfusiones
      case 46:
        return Category.Carne
      case 38:
        return Category.Carne
      case 47:
        return Category.Carne
      case 37:
        return Category.Carne
      case 42:
        return Category.Carne
      case 43:
        return Category.Carne
      case 44:
        return Category.Carne
      case 40:
        return Category.Carne
      case 45:
        return Category.Carne
      case 78:
        return Category.Cereales
      case 80:
        return Category.GalletasTortitas
      case 79:
        return Category.GalletasTortitas
      case 48:
        return Category.Charcuteria
      case 52:
        return Category.Charcuteria
      case 49:
        return Category.Charcuteria
      case 51:
        return Category.Charcuteria
      case 50:
        return Category.Charcuteria
      case 58:
        return Category.Charcuteria
      case 54:
        return Category.Charcuteria
      case 56:
        return Category.Charcuteria
      case 53:
        return Category.Charcuteria
      case 147:
        return Category.ArrocesPastaCongelados
      case 148:
        return Category.Carne
      case 154:
        return Category.HeladosHielo
      case 155:
        return Category.HeladosHielo
      case 150:
        return Category.Marisco
      case 149:
        return Category.Pescado
      case 151:
        return Category.Pizzas
      case 884:
        return Category.RebozadosCongelados
      case 152:
        return Category.TartasChurrosPasteles
      case 145:
        return Category.Verdura
      case 122:
        return Category.ConservasPescadoMoluscos
      case 123:
        return Category.ConservasPescadoMoluscos
      case 127:
        return Category.ConservasVerduraFrutas
      case 130:
        return Category.SopasCaldoCremas
      case 129:
        return Category.SopasCaldoCremas
      case 126:
        return Category.SopasCaldoCremas
      case 201:
        return Category.CuidadoCabello
      case 199:
        return Category.CuidadoCabello
      case 203:
        return Category.CuidadoCabello
      case 202:
        return Category.CuidadoCabello
      case 192:
        return Category.CuidadoFacial
      case 189:
        return Category.CuidadoCorporal
      case 185:
        return Category.CuidadoFacial
      case 191:
        return Category.CuidadoCorporal
      case 188:
        return Category.CuidadoCorporal
      case 187:
        return Category.CuidadoCorporal
      case 186:
        return Category.HijieneBucal
      case 190:
        return Category.CuidadoCorporal
      case 194:
        return Category.CuidadoCorporal
      case 196:
        return Category.PerfumeColonia
      case 198:
        return Category.CuidadoCorporal
      case 213:
        return Category.FitoterapiaParafarmacia
      case 214:
        return Category.FitoterapiaParafarmacia
      case 27:
        return Category.Fruta
      case 28:
        return Category.Verdura
      case 29:
        return Category.Verdura
      case 77:
        return Category.Huevos
      case 72:
        return Category.LecheBebidasVegetales
      case 75:
        return Category.MantequillaMargarina
      case 226:
        return Category.LimpiezaHogar
      case 237:
        return Category.LimpiezaHogar
      case 241:
        return Category.LimpiezaHogar
      case 234:
        return Category.LimpiezaHogar
      case 235:
        return Category.LimpiezaHogar
      case 233:
        return Category.LimpiezaHogar
      case 231:
        return Category.LimpiezaHogar
      case 230:
        return Category.LimpiezaHogar
      case 232:
        return Category.LimpiezaHogar
      case 229:
        return Category.LimpiezaHogar
      case 243:
        return Category.LimpiezaHogar
      case 238:
        return Category.LimpiezaHogar
      case 239:
        return Category.LimpiezaHogar
      case 244:
        return Category.LimpiezaHogar
      case 206:
        return Category.Maquillaje
      case 207:
        return Category.Maquillaje
      case 208:
        return Category.Maquillaje
      case 210:
        return Category.Maquillaje
      case 212:
        return Category.Maquillaje
      case 32:
        return Category.Marisco
      case 34:
        return Category.Pescado
      case 31:
        return Category.Pescado
      case 36:
        return Category.Marisco
      case 789:
        return Category.Pescado
      case 222:
        return Category.Mascotas
      case 221:
        return Category.Mascotas
      case 225:
        return Category.Mascotas
      case 65:
        return Category.Bolleria
      case 66:
        return Category.Bolleria
      case 69:
        return Category.HarinaPreparadoReposteria
      case 59:
        return Category.PanHorno
      case 60:
        return Category.PanMoldeTostado
      case 62:
        return Category.PanMoldeTostado
      case 64:
        return Category.Rosquilletas
      case 68:
        return Category.TartasChurrosPasteles
      case 71:
        return Category.VelasDecoracion
      case 897:
        return Category.PlatosPreparados
      case 138:
        return Category.Pizzas
      case 140:
        return Category.PlatosPreparados
      case 142:
        return Category.PlatosPreparados
      case 105:
        return Category.YoguresOtrosPostres
      case 110:
        return Category.YoguresOtrosPostres
      case 111:
        return Category.YoguresOtrosPostres
      case 106:
        return Category.YoguresOtrosPostres
      case 103:
        return Category.YoguresOtrosPostres
      case 109:
        return Category.YoguresOtrosPostres
      case 108:
        return Category.YoguresOtrosPostres
      case 104:
        return Category.YoguresOtrosPostres
      case 107:
        return Category.YoguresOtrosPostres
      case 99:
        return Category.Zumos
      case 100:
        return Category.Zumos
      case 143:
        return Category.Zumos
      case 98:
        return Category.Zumos
      default:
        return Category.Unknown
    }
  }
}
